abstract: Perl Module Compilation
author: Ingy döt Net <ingy@cpan.org>
build_requires: 
  Test::Base: 0.50
distribution_type: module
generated_by: Module::Install version 0.54
license: perl
name: Module-Compile
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6
version: 0.14
